import { AnyElement, DesignBlueprint, FontPack, Palette, TemplateContent } from './types';

let __id = 0;
const uid = (prefix = 'el') => `${prefix}_${Date.now().toString(36)}_${(__id++).toString(36)}`;

/* ============================================================
 * DESIGN 1 — كلاسيكي فاخر
 * ============================================================ */
const classicLuxe: DesignBlueprint = {
  key: 'classic-luxe',
  name: 'كلاسيكي فاخر',
  description: 'تصميم خالد بإطارات ذهبية أنيقة',
  category: 'classic',
  canvas: { width: 800, height: 1200, background: '#FBF6E6' },
  thumbnailGradient: 'linear-gradient(135deg, #FBF6E6 0%, #F5D78E 100%)',
  build: (p, f, c) => [
    {
      id: uid('frame'),
      type: 'shape',
      shape: 'rect',
      x: 40,
      y: 40,
      width: 720,
      height: 1120,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: 'transparent',
      stroke: p.primary,
      strokeWidth: 2,
      borderRadius: 8
    },
    {
      id: uid('frame2'),
      type: 'shape',
      shape: 'rect',
      x: 55,
      y: 55,
      width: 690,
      height: 1090,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: 'transparent',
      stroke: p.secondary,
      strokeWidth: 1,
      borderRadius: 4
    },
    {
      id: uid('title'),
      type: 'text',
      x: 100,
      y: 160,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'دعوة زفاف',
      fontKey: f.key,
      fontSize: 56,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.2,
      letterSpacing: 4
    },
    {
      id: uid('ornament'),
      type: 'divider',
      x: 250,
      y: 270,
      width: 300,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'ornament-1',
      color: p.primary,
      thickness: 2
    },
    {
      id: uid('parents'),
      type: 'text',
      x: 80,
      y: 340,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.parents,
      fontKey: f.key,
      fontSize: 22,
      fontWeight: 400,
      color: p.muted,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 460,
      width: 640,
      height: 120,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n&\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 64,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 700,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 100,
      y: 880,
      width: 600,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 600,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 100,
      y: 960,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 2 — عربي إسلامي
 * ============================================================ */
const arabicIslamic: DesignBlueprint = {
  key: 'arabic-islamic',
  name: 'عربي إسلامي',
  description: 'زخارف عربية إسلامية فاخرة',
  category: 'arabic',
  canvas: { width: 800, height: 1200, background: '#F4F1E8' },
  thumbnailGradient: 'linear-gradient(135deg, #0F5132 0%, #C9A84C 100%)',
  build: (p, f, c) => [
    {
      id: uid('bg'),
      type: 'shape',
      shape: 'rect',
      x: 0,
      y: 0,
      width: 800,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('bg2'),
      type: 'shape',
      shape: 'rect',
      x: 0,
      y: 1000,
      width: 800,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('bismillah'),
      type: 'text',
      x: 80,
      y: 60,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'بسم الله الرحمن الرحيم',
      fontKey: f.key,
      fontSize: 36,
      fontWeight: 700,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('verse'),
      type: 'text',
      x: 80,
      y: 250,
      width: 640,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: '﴿ وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا ﴾',
      fontKey: f.key,
      fontSize: 22,
      fontWeight: 400,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 300,
      y: 390,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'ornament-2',
      color: p.primary,
      thickness: 2
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 480,
      width: 640,
      height: 140,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName} & ${c.brideName}`,
      fontKey: f.key,
      fontSize: 54,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 680,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 830,
      width: 640,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 26,
      fontWeight: 600,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 1040,
      width: 640,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName} — ${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 500,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 3 — عصري مينيمال
 * ============================================================ */
const modernMinimal: DesignBlueprint = {
  key: 'modern-minimal',
  name: 'عصري مينيمال',
  description: 'بساطة عصرية بأناقة',
  category: 'modern',
  canvas: { width: 800, height: 1200, background: '#FAFAFA' },
  thumbnailGradient: 'linear-gradient(135deg, #FAFAFA 0%, #0A0A0A 100%)',
  build: (p, f, c) => [
    {
      id: uid('line-top'),
      type: 'shape',
      shape: 'rect',
      x: 350,
      y: 150,
      width: 100,
      height: 2,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('save'),
      type: 'text',
      x: 80,
      y: 200,
      width: 640,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'احفظ التاريخ',
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.muted,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 8
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 380,
      width: 640,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 72,
      fontWeight: 300,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 4
    },
    {
      id: uid('line-mid'),
      type: 'shape',
      shape: 'rect',
      x: 300,
      y: 680,
      width: 200,
      height: 1,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.muted,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 720,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 32,
      fontWeight: 500,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 880,
      width: 640,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.7,
      letterSpacing: 1
    },
    {
      id: uid('line-bot'),
      type: 'shape',
      shape: 'rect',
      x: 350,
      y: 1050,
      width: 100,
      height: 2,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    }
  ]
};

/* ============================================================
 * DESIGN 4 — رومانسي
 * ============================================================ */
const romanticBlush: DesignBlueprint = {
  key: 'romantic-blush',
  name: 'رومانسي',
  description: 'وردي ناعم بلمسات ذهبية',
  category: 'romantic',
  canvas: { width: 800, height: 1200, background: '#FFF5F0' },
  thumbnailGradient: 'linear-gradient(135deg, #FFF5F0 0%, #C2185B 100%)',
  build: (p, f, c) => [
    {
      id: uid('circle-bg'),
      type: 'shape',
      shape: 'circle',
      x: -100,
      y: -100,
      width: 350,
      height: 350,
      rotation: 0,
      opacity: 0.15,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 999
    },
    {
      id: uid('circle-bg2'),
      type: 'shape',
      shape: 'circle',
      x: 550,
      y: 950,
      width: 400,
      height: 400,
      rotation: 0,
      opacity: 0.15,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.accent,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 999
    },
    {
      id: uid('heart'),
      type: 'icon',
      x: 370,
      y: 120,
      width: 60,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      name: 'Heart',
      color: p.primary
    },
    {
      id: uid('title'),
      type: 'text',
      x: 80,
      y: 220,
      width: 640,
      height: 70,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'بأجمل لحظات الحب',
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 400,
      color: p.muted,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 360,
      width: 640,
      height: 180,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\nو\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 60,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 2
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 280,
      y: 660,
      width: 240,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'ornament-3',
      color: p.accent,
      thickness: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 720,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 880,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 600,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 980,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 5 — بوهيمي
 * ============================================================ */
const bohemian: DesignBlueprint = {
  key: 'bohemian',
  name: 'بوهيمي',
  description: 'دفء بيج ونحاسي',
  category: 'boho',
  canvas: { width: 800, height: 1200, background: '#F5EBDA' },
  thumbnailGradient: 'linear-gradient(135deg, #E8C9A0 0%, #A0522D 100%)',
  build: (p, f, c) => [
    {
      id: uid('arch'),
      type: 'shape',
      shape: 'rect',
      x: 150,
      y: 80,
      width: 500,
      height: 700,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: 'transparent',
      stroke: p.primary,
      strokeWidth: 2,
      borderRadius: 250
    },
    {
      id: uid('title'),
      type: 'text',
      x: 100,
      y: 180,
      width: 600,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'تجمعنا الفرحة',
      fontKey: f.key,
      fontSize: 24,
      fontWeight: 400,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 4
    },
    {
      id: uid('names'),
      type: 'text',
      x: 100,
      y: 340,
      width: 600,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n♥\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 56,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 1
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 280,
      y: 600,
      width: 240,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'dots',
      color: p.primary,
      thickness: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 660,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.7,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 100,
      y: 880,
      width: 600,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 26,
      fontWeight: 600,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 100,
      y: 980,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 6 — ملكي
 * ============================================================ */
const royal: DesignBlueprint = {
  key: 'royal',
  name: 'ملكي',
  description: 'كحلي عميق وذهب فاخر',
  category: 'royal',
  canvas: { width: 800, height: 1200, background: '#0A1A3F' },
  thumbnailGradient: 'linear-gradient(135deg, #0A1A3F 0%, #C9A84C 100%)',
  build: (p, f, c) => [
    {
      id: uid('frame'),
      type: 'shape',
      shape: 'rect',
      x: 40,
      y: 40,
      width: 720,
      height: 1120,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: 'transparent',
      stroke: p.secondary,
      strokeWidth: 3,
      borderRadius: 12
    },
    {
      id: uid('crown'),
      type: 'icon',
      x: 370,
      y: 100,
      width: 60,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      name: 'Crown',
      color: p.secondary
    },
    {
      id: uid('title'),
      type: 'text',
      x: 80,
      y: 200,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'حفل الزفاف الملكي',
      fontKey: f.key,
      fontSize: 36,
      fontWeight: 700,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 3
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 280,
      y: 320,
      width: 240,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'ornament-1',
      color: p.secondary,
      thickness: 2
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 420,
      width: 640,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n&\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 64,
      fontWeight: 700,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 720,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: '#E8DCC0',
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 900,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 700,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 1000,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 500,
      color: '#C0C8DC',
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 7 — طبيعي
 * ============================================================ */
const natural: DesignBlueprint = {
  key: 'natural',
  name: 'طبيعي',
  description: 'أخضر هادئ مع بيج طبيعي',
  category: 'nature',
  canvas: { width: 800, height: 1200, background: '#F3EFE3' },
  thumbnailGradient: 'linear-gradient(135deg, #D9C9A8 0%, #5A7A52 100%)',
  build: (p, f, c) => [
    {
      id: uid('leaf1'),
      type: 'icon',
      x: 60,
      y: 80,
      width: 100,
      height: 100,
      rotation: -25,
      opacity: 0.6,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      name: 'Leaf',
      color: p.primary
    },
    {
      id: uid('leaf2'),
      type: 'icon',
      x: 640,
      y: 80,
      width: 100,
      height: 100,
      rotation: 25,
      opacity: 0.6,
      zIndex: 2,
      locked: false,
      visible: true,
      flipH: true,
      flipV: false,
      name: 'Leaf',
      color: p.primary
    },
    {
      id: uid('title'),
      type: 'text',
      x: 80,
      y: 240,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'بكل حب ندعوكم',
      fontKey: f.key,
      fontSize: 24,
      fontWeight: 400,
      color: p.muted,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 3
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 380,
      width: 640,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n&\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 60,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 1
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 280,
      y: 660,
      width: 240,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'line',
      color: p.accent,
      thickness: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 720,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.7,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 880,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 600,
      color: p.accent,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 980,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 8 — راقي رمادي
 * ============================================================ */
const elegantGrey: DesignBlueprint = {
  key: 'elegant-grey',
  name: 'راقي',
  description: 'رمادي فاخر بلمسات فضية',
  category: 'elegant',
  canvas: { width: 800, height: 1200, background: '#F0F2F5' },
  thumbnailGradient: 'linear-gradient(135deg, #C0C5CC 0%, #5A6573 100%)',
  build: (p, f, c) => [
    {
      id: uid('band-top'),
      type: 'shape',
      shape: 'rect',
      x: 0,
      y: 0,
      width: 800,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('band-bot'),
      type: 'shape',
      shape: 'rect',
      x: 0,
      y: 1192,
      width: 800,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('title'),
      type: 'text',
      x: 80,
      y: 180,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'دعوة زفاف',
      fontKey: f.key,
      fontSize: 22,
      fontWeight: 500,
      color: p.muted,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 8
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 360,
      width: 640,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 68,
      fontWeight: 300,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 2
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 320,
      y: 640,
      width: 160,
      height: 2,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'line',
      color: p.muted,
      thickness: 1
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 700,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 880,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 26,
      fontWeight: 500,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 980,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 1
    }
  ]
};

/* ============================================================
 * DESIGN 9 — شرقي بورجوندي
 * ============================================================ */
const orientalBurgundy: DesignBlueprint = {
  key: 'oriental-burgundy',
  name: 'شرقي',
  description: 'بورجوندي شرقي مع ذهب',
  category: 'oriental',
  canvas: { width: 800, height: 1200, background: '#F8F0E3' },
  thumbnailGradient: 'linear-gradient(135deg, #7B1F2C 0%, #C9A84C 100%)',
  build: (p, f, c) => [
    {
      id: uid('frame-tl'),
      type: 'shape',
      shape: 'rect',
      x: 30,
      y: 30,
      width: 200,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('frame-br'),
      type: 'shape',
      shape: 'rect',
      x: 570,
      y: 970,
      width: 200,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('title'),
      type: 'text',
      x: 80,
      y: 260,
      width: 640,
      height: 70,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'يتشرفون بدعوتكم',
      fontKey: f.key,
      fontSize: 30,
      fontWeight: 600,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 2
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 280,
      y: 350,
      width: 240,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'ornament-2',
      color: p.secondary,
      thickness: 2
    },
    {
      id: uid('names'),
      type: 'text',
      x: 80,
      y: 440,
      width: 640,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n&\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 60,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: 2
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 100,
      y: 720,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.8,
      letterSpacing: 0
    },
    {
      id: uid('date'),
      type: 'text',
      x: 80,
      y: 880,
      width: 640,
      height: 60,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 700,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 1
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 80,
      y: 970,
      width: 640,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 500,
      color: p.text,
      textAlign: 'center',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

/* ============================================================
 * DESIGN 10 — معاصر
 * ============================================================ */
const contemporary: DesignBlueprint = {
  key: 'contemporary',
  name: 'معاصر',
  description: 'أزرق معاصر بأبيض ناصع',
  category: 'modern',
  canvas: { width: 800, height: 1200, background: '#FFFFFF' },
  thumbnailGradient: 'linear-gradient(135deg, #1E5B8C 0%, #E8F0F7 100%)',
  build: (p, f, c) => [
    {
      id: uid('side-band'),
      type: 'shape',
      shape: 'rect',
      x: 0,
      y: 0,
      width: 120,
      height: 1200,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      fill: p.primary,
      stroke: 'transparent',
      strokeWidth: 0,
      borderRadius: 0
    },
    {
      id: uid('vertical'),
      type: 'text',
      x: 20,
      y: 400,
      width: 80,
      height: 400,
      rotation: 270,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'WEDDING INVITATION',
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 600,
      color: p.secondary,
      textAlign: 'center',
      lineHeight: 1.4,
      letterSpacing: 8
    },
    {
      id: uid('label'),
      type: 'text',
      x: 160,
      y: 200,
      width: 600,
      height: 40,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'دعوة زفاف',
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 500,
      color: p.muted,
      textAlign: 'right',
      lineHeight: 1.4,
      letterSpacing: 4
    },
    {
      id: uid('names'),
      type: 'text',
      x: 160,
      y: 320,
      width: 600,
      height: 200,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.groomName}\n${c.brideName}`,
      fontKey: f.key,
      fontSize: 64,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'right',
      lineHeight: 1.2,
      letterSpacing: 0
    },
    {
      id: uid('div'),
      type: 'divider',
      x: 160,
      y: 580,
      width: 80,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      style: 'line',
      color: p.primary,
      thickness: 4
    },
    {
      id: uid('msg'),
      type: 'text',
      x: 160,
      y: 620,
      width: 600,
      height: 120,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.message,
      fontKey: f.key,
      fontSize: 20,
      fontWeight: 400,
      color: p.text,
      textAlign: 'right',
      lineHeight: 1.7,
      letterSpacing: 0
    },
    {
      id: uid('date-label'),
      type: 'text',
      x: 160,
      y: 820,
      width: 600,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'التاريخ',
      fontKey: f.key,
      fontSize: 14,
      fontWeight: 600,
      color: p.muted,
      textAlign: 'right',
      lineHeight: 1.4,
      letterSpacing: 3
    },
    {
      id: uid('date'),
      type: 'text',
      x: 160,
      y: 850,
      width: 600,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: c.weddingDate,
      fontKey: f.key,
      fontSize: 28,
      fontWeight: 700,
      color: p.primary,
      textAlign: 'right',
      lineHeight: 1.4,
      letterSpacing: 0
    },
    {
      id: uid('venue-label'),
      type: 'text',
      x: 160,
      y: 960,
      width: 600,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: 'المكان',
      fontKey: f.key,
      fontSize: 14,
      fontWeight: 600,
      color: p.muted,
      textAlign: 'right',
      lineHeight: 1.4,
      letterSpacing: 3
    },
    {
      id: uid('venue'),
      type: 'text',
      x: 160,
      y: 990,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
      flipH: false,
      flipV: false,
      content: `${c.venueName}\n${c.venueAddress}`,
      fontKey: f.key,
      fontSize: 18,
      fontWeight: 500,
      color: p.text,
      textAlign: 'right',
      lineHeight: 1.6,
      letterSpacing: 0
    }
  ]
};

export const DESIGNS: DesignBlueprint[] = [
  classicLuxe,
  arabicIslamic,
  modernMinimal,
  romanticBlush,
  bohemian,
  royal,
  natural,
  elegantGrey,
  orientalBurgundy,
  contemporary
];

export function getDesign(key: string): DesignBlueprint {
  return DESIGNS.find((d) => d.key === key) || DESIGNS[0];
}
